
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hunter?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: rootroot
    type: com.alibaba.druid.pool.DruidDataSource
  freemarker:
    checkTemplateLocation: false

mybatis:
  typeAliasesPackage: com.example.demo.bean
  mapperLocations: classpath:com/example/demo/mapper/xml/*.xml

server:
  port: 8081